# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-17 01:30:13
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def CAD2GISV1Model(
        Project_Name,
        Coordinate_System_of_the_CAD_Data_prj_,
        Input_CAD_Folder="C:\\Users\\", 
        Output_Folder="C:\\Users\\", 
        Auto_Add_To_Map=True, 
        Search_subfolders=True):  # CAD2GISV1Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"C:\NMDOT_CAD2GIS_PRODUCT\NMDOT_CAD2GIS_PRODUCT.atbx")

    # Process: CADToGDBWrapper (CADToGDBWrapper) (NMDOTCAD2GISPRODUCTatbx)
    Output_GDB, Output_Staging_Dataset = arcpy.NMDOTCAD2GISPRODUCTatbx.CADToGDBWrapper(Input_CAD_Folder=Input_CAD_Folder.__str__().format(**locals(),**globals())if isinstance(Input_CAD_Folder, str) else Input_CAD_Folder, Output_Folder=Output_Folder.__str__().format(**locals(),**globals())if isinstance(Output_Folder, str) else Output_Folder, Projection_File=Coordinate_System_of_the_CAD_Data_prj_.__str__().format(**locals(),**globals())if isinstance(Coordinate_System_of_the_CAD_Data_prj_, str) else Coordinate_System_of_the_CAD_Data_prj_, Project_Name=Project_Name.__str__().format(**locals(),**globals())if isinstance(Project_Name, str) else Project_Name, Auto_Add_To_Map=Auto_Add_To_Map.__str__().format(**locals(),**globals())if isinstance(Auto_Add_To_Map, str) else Auto_Add_To_Map, Search_subfolders=Search_subfolders.__str__().format(**locals(),**globals())if isinstance(Search_subfolders, str) else Search_subfolders)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\NMDOT_CAD2GIS_PRODUCT\\NMDOT_CAD2GIS_PRODUCT.gdb", workspace="C:\\NMDOT_CAD2GIS_PRODUCT\\NMDOT_CAD2GIS_PRODUCT.gdb"):
        CAD2GISV1Model(*argv[1:])
